name: Lint Lua and Python

on:
  workflow_call:

jobs:
  lint-lua:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - run: nix run .#lint-lua

  lint-python:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: nixbuild/nix-quick-install-action@v34

      - run: nix run .#lint-python

